scrape_configs:
  - job_name: 'propostaot_metricas'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['propostaot:8475'] #servidor da aplicação
    scrape_interval: 5m
    scrape_timeout: 1m